# do not import all endpoints into this module because that uses a lot of memory and stack frames
# if you need the ability to import all endpoints from this module, import them with
# from soundcloud_python_sdk.apis.path_to_api import path_to_api

import enum


class PathValues(str, enum.Enum):
    CONNECT = "/connect"
    OAUTH2_TOKEN = "/oauth2/token"
    ME = "/me"
    ME_ACTIVITIES = "/me/activities"
    ME_ACTIVITIES_ALL_OWN = "/me/activities/all/own"
    ME_ACTIVITIES_TRACKS = "/me/activities/tracks"
    ME_LIKES_TRACKS = "/me/likes/tracks"
    ME_LIKES_PLAYLISTS = "/me/likes/playlists"
    ME_FOLLOWINGS = "/me/followings"
    ME_FOLLOWINGS_TRACKS = "/me/followings/tracks"
    ME_FOLLOWINGS_USER_ID = "/me/followings/{user_id}"
    ME_FOLLOWERS = "/me/followers"
    ME_FOLLOWERS_FOLLOWER_ID = "/me/followers/{follower_id}"
    ME_PLAYLISTS = "/me/playlists"
    ME_TRACKS = "/me/tracks"
    TRACKS = "/tracks"
    PLAYLISTS = "/playlists"
    USERS = "/users"
    PLAYLISTS_PLAYLIST_ID = "/playlists/{playlist_id}"
    PLAYLISTS_PLAYLIST_ID_TRACKS = "/playlists/{playlist_id}/tracks"
    PLAYLISTS_PLAYLIST_ID_REPOSTERS = "/playlists/{playlist_id}/reposters"
    TRACKS_TRACK_ID = "/tracks/{track_id}"
    TRACKS_TRACK_ID_STREAMS = "/tracks/{track_id}/streams"
    TRACKS_TRACK_ID_COMMENTS = "/tracks/{track_id}/comments"
    TRACKS_TRACK_ID_FAVORITERS = "/tracks/{track_id}/favoriters"
    TRACKS_TRACK_ID_REPOSTERS = "/tracks/{track_id}/reposters"
    TRACKS_TRACK_ID_RELATED = "/tracks/{track_id}/related"
    RESOLVE = "/resolve"
    USERS_USER_ID = "/users/{user_id}"
    USERS_USER_ID_FAVORITES = "/users/{user_id}/favorites"
    USERS_USER_ID_FOLLOWERS = "/users/{user_id}/followers"
    USERS_USER_ID_FOLLOWINGS = "/users/{user_id}/followings"
    USERS_USER_ID_FOLLOWINGS_FOLLOWING_ID = "/users/{user_id}/followings/{following_id}"
    USERS_USER_ID_PLAYLISTS = "/users/{user_id}/playlists"
    USERS_USER_ID_TRACKS = "/users/{user_id}/tracks"
    USERS_USER_ID_WEBPROFILES = "/users/{user_id}/web-profiles"
    USERS_USER_ID_LIKES_TRACKS = "/users/{user_id}/likes/tracks"
    USERS_USER_ID_LIKES_PLAYLISTS = "/users/{user_id}/likes/playlists"
    LIKES_TRACKS_TRACK_ID = "/likes/tracks/{track_id}"
    LIKES_PLAYLISTS_PLAYLIST_ID = "/likes/playlists/{playlist_id}"
    REPOSTS_TRACKS_TRACK_ID = "/reposts/tracks/{track_id}"
    REPOSTS_PLAYLISTS_PLAYLIST_ID = "/reposts/playlists/{playlist_id}"
