# coding: utf-8

"""
    SoundCloud Public API Specification

    Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

    The version of the OpenAPI document: 1.0.0
    Created by: https://github.com/soundcloud/api
"""

from soundcloud_python_sdk.paths.likes_playlists_playlist_id.post import Playlist
from soundcloud_python_sdk.paths.likes_tracks_track_id.post import TrackAction
from soundcloud_python_sdk.paths.likes_playlists_playlist_id.delete import UnlikePlaylist
from soundcloud_python_sdk.paths.likes_tracks_track_id.delete import UnlikeTrack
from soundcloud_python_sdk.apis.tags.likes_api_raw import LikesApiRaw


class LikesApi(
    Playlist,
    TrackAction,
    UnlikePlaylist,
    UnlikeTrack,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: LikesApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = LikesApiRaw(api_client)
