# coding: utf-8

"""
    SoundCloud Public API Specification

    Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

    The version of the OpenAPI document: 1.0.0
    Created by: https://github.com/soundcloud/api
"""

from soundcloud_python_sdk.paths.likes_playlists_playlist_id.post import PlaylistRaw
from soundcloud_python_sdk.paths.likes_tracks_track_id.post import TrackActionRaw
from soundcloud_python_sdk.paths.likes_playlists_playlist_id.delete import UnlikePlaylistRaw
from soundcloud_python_sdk.paths.likes_tracks_track_id.delete import UnlikeTrackRaw


class LikesApiRaw(
    PlaylistRaw,
    TrackActionRaw,
    UnlikePlaylistRaw,
    UnlikeTrackRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
