# coding: utf-8

"""
    SoundCloud Public API Specification

    Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

    The version of the OpenAPI document: 1.0.0
    Created by: https://github.com/soundcloud/api
"""

from soundcloud_python_sdk.paths.me_followings_user_id.delete import DeleteFollowedUser
from soundcloud_python_sdk.paths.me_followings_user_id.put import FollowUser
from soundcloud_python_sdk.paths.me_activities.get import GetActivities
from soundcloud_python_sdk.paths.me_followings_user_id.get import GetFollowedUser
from soundcloud_python_sdk.paths.me_followings.get import GetFollowedUsers
from soundcloud_python_sdk.paths.me_followers_follower_id.get import GetFollowerById
from soundcloud_python_sdk.paths.me_followers.get import GetFollowersList
from soundcloud_python_sdk.paths.me_likes_playlists.get import GetLikedPlaylists
from soundcloud_python_sdk.paths.me_activities_all_own.get import GetRecentActivities
from soundcloud_python_sdk.paths.me_activities_tracks.get import GetRecentTracks
from soundcloud_python_sdk.paths.me.get import GetUserInformation
from soundcloud_python_sdk.paths.me_followings_tracks.get import ListFollowedTracks
from soundcloud_python_sdk.paths.me_likes_tracks.get import ListLikedTracks
from soundcloud_python_sdk.paths.me_playlists.get import ListPlaylistsInfoTracksOwner
from soundcloud_python_sdk.paths.me_tracks.get import ListUserTracks
from soundcloud_python_sdk.apis.tags.me_api_raw import MeApiRaw


class MeApi(
    DeleteFollowedUser,
    FollowUser,
    GetActivities,
    GetFollowedUser,
    GetFollowedUsers,
    GetFollowerById,
    GetFollowersList,
    GetLikedPlaylists,
    GetRecentActivities,
    GetRecentTracks,
    GetUserInformation,
    ListFollowedTracks,
    ListLikedTracks,
    ListPlaylistsInfoTracksOwner,
    ListUserTracks,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: MeApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = MeApiRaw(api_client)
