# coding: utf-8

"""
    SoundCloud Public API Specification

    Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

    The version of the OpenAPI document: 1.0.0
    Created by: https://github.com/soundcloud/api
"""

from soundcloud_python_sdk.paths.me_followings_user_id.delete import DeleteFollowedUserRaw
from soundcloud_python_sdk.paths.me_followings_user_id.put import FollowUserRaw
from soundcloud_python_sdk.paths.me_activities.get import GetActivitiesRaw
from soundcloud_python_sdk.paths.me_followings_user_id.get import GetFollowedUserRaw
from soundcloud_python_sdk.paths.me_followings.get import GetFollowedUsersRaw
from soundcloud_python_sdk.paths.me_followers_follower_id.get import GetFollowerByIdRaw
from soundcloud_python_sdk.paths.me_followers.get import GetFollowersListRaw
from soundcloud_python_sdk.paths.me_likes_playlists.get import GetLikedPlaylistsRaw
from soundcloud_python_sdk.paths.me_activities_all_own.get import GetRecentActivitiesRaw
from soundcloud_python_sdk.paths.me_activities_tracks.get import GetRecentTracksRaw
from soundcloud_python_sdk.paths.me.get import GetUserInformationRaw
from soundcloud_python_sdk.paths.me_followings_tracks.get import ListFollowedTracksRaw
from soundcloud_python_sdk.paths.me_likes_tracks.get import ListLikedTracksRaw
from soundcloud_python_sdk.paths.me_playlists.get import ListPlaylistsInfoTracksOwnerRaw
from soundcloud_python_sdk.paths.me_tracks.get import ListUserTracksRaw


class MeApiRaw(
    DeleteFollowedUserRaw,
    FollowUserRaw,
    GetActivitiesRaw,
    GetFollowedUserRaw,
    GetFollowedUsersRaw,
    GetFollowerByIdRaw,
    GetFollowersListRaw,
    GetLikedPlaylistsRaw,
    GetRecentActivitiesRaw,
    GetRecentTracksRaw,
    GetUserInformationRaw,
    ListFollowedTracksRaw,
    ListLikedTracksRaw,
    ListPlaylistsInfoTracksOwnerRaw,
    ListUserTracksRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
