# coding: utf-8

"""
    SoundCloud Public API Specification

    Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

    The version of the OpenAPI document: 1.0.0
    Created by: https://github.com/soundcloud/api
"""

from soundcloud_python_sdk.paths.resolve.get import ResolveSoundcloudUrls
from soundcloud_python_sdk.apis.tags.miscellaneous_api_raw import MiscellaneousApiRaw


class MiscellaneousApi(
    ResolveSoundcloudUrls,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: MiscellaneousApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = MiscellaneousApiRaw(api_client)
