# coding: utf-8

"""
    SoundCloud Public API Specification

    Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

    The version of the OpenAPI document: 1.0.0
    Created by: https://github.com/soundcloud/api
"""

from soundcloud_python_sdk.paths.playlists.post import CreateNewPlaylistRaw
from soundcloud_python_sdk.paths.playlists_playlist_id.delete import DeletePlaylistRaw
from soundcloud_python_sdk.paths.playlists_playlist_id.get import GetPlaylistByIdRaw
from soundcloud_python_sdk.paths.playlists_playlist_id_tracks.get import GetTracksRaw
from soundcloud_python_sdk.paths.playlists_playlist_id_reposters.get import ListRepostersRaw
from soundcloud_python_sdk.paths.playlists_playlist_id.put import UpdatePlaylistByIdRaw


class PlaylistsApiRaw(
    CreateNewPlaylistRaw,
    DeletePlaylistRaw,
    GetPlaylistByIdRaw,
    GetTracksRaw,
    ListRepostersRaw,
    UpdatePlaylistByIdRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
