# coding: utf-8

"""
    SoundCloud Public API Specification

    Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

    The version of the OpenAPI document: 1.0.0
    Created by: https://github.com/soundcloud/api
"""

from soundcloud_python_sdk.paths.reposts_playlists_playlist_id.post import PlaylistAsAuthenticatedUser
from soundcloud_python_sdk.paths.reposts_tracks_track_id.delete import RemoveRepost
from soundcloud_python_sdk.paths.reposts_playlists_playlist_id.delete import RemoveRepostOnPlaylist
from soundcloud_python_sdk.paths.reposts_tracks_track_id.post import TrackAsAuthenticatedUser
from soundcloud_python_sdk.apis.tags.reposts_api_raw import RepostsApiRaw


class RepostsApi(
    PlaylistAsAuthenticatedUser,
    RemoveRepost,
    RemoveRepostOnPlaylist,
    TrackAsAuthenticatedUser,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: RepostsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = RepostsApiRaw(api_client)
