# coding: utf-8

"""
    SoundCloud Public API Specification

    Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

    The version of the OpenAPI document: 1.0.0
    Created by: https://github.com/soundcloud/api
"""

from soundcloud_python_sdk.paths.tracks.get import ByQueryRaw
from soundcloud_python_sdk.paths.playlists.get import ByQuery0Raw
from soundcloud_python_sdk.paths.users.get import UserQueryRaw


class SearchApiRaw(
    ByQueryRaw,
    ByQuery0Raw,
    UserQueryRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
