# coding: utf-8

"""
    SoundCloud Public API Specification

    Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

    The version of the OpenAPI document: 1.0.0
    Created by: https://github.com/soundcloud/api
"""

from soundcloud_python_sdk.paths.tracks.get import ByQuery
from soundcloud_python_sdk.paths.playlists.get import ByQuery0
from soundcloud_python_sdk.paths.users.get import UserQuery
from soundcloud_python_sdk.apis.tags.search_api_raw import SearchApiRaw


class SearchApi(
    ByQuery,
    ByQuery0,
    UserQuery,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: SearchApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = SearchApiRaw(api_client)
