# coding: utf-8

"""
    SoundCloud Public API Specification

    Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

    The version of the OpenAPI document: 1.0.0
    Created by: https://github.com/soundcloud/api
"""

from soundcloud_python_sdk.paths.tracks_track_id_comments.post import CreateComment
from soundcloud_python_sdk.paths.tracks_track_id.delete import DeleteTrack
from soundcloud_python_sdk.paths.tracks_track_id.get import GetById
from soundcloud_python_sdk.paths.tracks_track_id_comments.get import GetComments
from soundcloud_python_sdk.paths.tracks_track_id_favoriters.get import GetFavoriters
from soundcloud_python_sdk.paths.tracks_track_id_related.get import GetRelatedTracks
from soundcloud_python_sdk.paths.tracks_track_id_streams.get import GetStreamableUrls
from soundcloud_python_sdk.paths.tracks_track_id_reposters.get import ListReposters
from soundcloud_python_sdk.paths.tracks_track_id.put import UpdateTrackInformation
from soundcloud_python_sdk.paths.tracks.post import UploadNewTrack
from soundcloud_python_sdk.apis.tags.tracks_api_raw import TracksApiRaw


class TracksApi(
    CreateComment,
    DeleteTrack,
    GetById,
    GetComments,
    GetFavoriters,
    GetRelatedTracks,
    GetStreamableUrls,
    ListReposters,
    UpdateTrackInformation,
    UploadNewTrack,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TracksApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TracksApiRaw(api_client)
