# coding: utf-8

"""
    SoundCloud Public API Specification

    Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

    The version of the OpenAPI document: 1.0.0
    Created by: https://github.com/soundcloud/api
"""

from soundcloud_python_sdk.paths.users_user_id_followers.get import GetFollowers
from soundcloud_python_sdk.paths.users_user_id_followings_following_id.get import GetFollowingById
from soundcloud_python_sdk.paths.users_user_id.get import GetUser
from soundcloud_python_sdk.paths.users_user_id_followings.get import GetUserFollowings
from soundcloud_python_sdk.paths.users_user_id_playlists.get import GetUserPlaylists
from soundcloud_python_sdk.paths.users_user_id_tracks.get import GetUserTracks
from soundcloud_python_sdk.paths.users_user_id_web_profiles.get import GetUserWebProfiles
from soundcloud_python_sdk.paths.users_user_id_favorites.get import ListFavorites
from soundcloud_python_sdk.paths.users_user_id_likes_playlists.get import ListLikedPlaylists
from soundcloud_python_sdk.paths.users_user_id_likes_tracks.get import ListLikedTracks
from soundcloud_python_sdk.apis.tags.users_api_raw import UsersApiRaw


class UsersApi(
    GetFollowers,
    GetFollowingById,
    GetUser,
    GetUserFollowings,
    GetUserPlaylists,
    GetUserTracks,
    GetUserWebProfiles,
    ListFavorites,
    ListLikedPlaylists,
    ListLikedTracks,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UsersApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UsersApiRaw(api_client)
