# coding: utf-8

"""
    SoundCloud Public API Specification

    Discover and play over 320 million music tracks. Join the world’s largest online community of artists, bands, DJs, and audio creators.

    The version of the OpenAPI document: 1.0.0
    Created by: https://github.com/soundcloud/api
"""

from soundcloud_python_sdk.paths.users_user_id_followers.get import GetFollowersRaw
from soundcloud_python_sdk.paths.users_user_id_followings_following_id.get import GetFollowingByIdRaw
from soundcloud_python_sdk.paths.users_user_id.get import GetUserRaw
from soundcloud_python_sdk.paths.users_user_id_followings.get import GetUserFollowingsRaw
from soundcloud_python_sdk.paths.users_user_id_playlists.get import GetUserPlaylistsRaw
from soundcloud_python_sdk.paths.users_user_id_tracks.get import GetUserTracksRaw
from soundcloud_python_sdk.paths.users_user_id_web_profiles.get import GetUserWebProfilesRaw
from soundcloud_python_sdk.paths.users_user_id_favorites.get import ListFavoritesRaw
from soundcloud_python_sdk.paths.users_user_id_likes_playlists.get import ListLikedPlaylistsRaw
from soundcloud_python_sdk.paths.users_user_id_likes_tracks.get import ListLikedTracksRaw


class UsersApiRaw(
    GetFollowersRaw,
    GetFollowingByIdRaw,
    GetUserRaw,
    GetUserFollowingsRaw,
    GetUserPlaylistsRaw,
    GetUserTracksRaw,
    GetUserWebProfilesRaw,
    ListFavoritesRaw,
    ListLikedPlaylistsRaw,
    ListLikedTracksRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
